on:
  push:
    branches: main

name: pkgdown

jobs:
  pkgdown:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: dawidd6/action-download-artifact@v2
        with:
        # Optional, GitHub token, a Personal Access Token with `public_repo` scope if needed
        # Required, if artifact is from a different repo
        # Required, if repo is private a Personal Access Token with `repo` scope is needed
        # github_token: ${{secrets.GITHUB_TOKEN}}
        # Required, workflow file name or ID
        workflow: R CMD Check (ubuntu-20.04 (release))
        # Optional, will use the branch
        branch: master
        # Optional, defaults to all types
        event: push
        # Optional, uploaded artifact name,
        # will download all artifacts if not specified
        # and extract them in respective subdirectories
        # https://github.com/actions/download-artifact#download-all-artifacts
        # name: check
        # Optional, check the workflow run whether it has an artifact
        # then will get the last available artifact from previous workflow
        # default false, just try to download from the last one
        check_artifacts:  false
        # Optional, search for the last workflow run whose stored an artifact named as in `name` input
        # default false
        search_artifacts: false

      - uses: r-lib/actions/setup-r@master

      - uses: r-lib/actions/setup-pandoc@master

      - name: Query dependencies
        run: |
          install.packages('remotes')
          saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
          writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")
        shell: Rscript {0}

      - name: Cache R packages
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-

      - name: Install dependencies
        run: |
          remotes::install_deps(dependencies = TRUE)
          install.packages("pkgdown")
          remotes::install_github("mlr-org/mlr3pkgdowntemplate")
        shell: Rscript {0}

      - name: Install package
        run: R CMD INSTALL .

      - name: Deploy package
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          Rscript -e 'pkgdown::deploy_to_branch(new_process = FALSE)'
